# Generated by Django 3.1.1 on 2020-11-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercuri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='hospitalstaff',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='fullName',
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='title',
            field=models.CharField(default='Nurse', max_length=60),
        ),
    ]
