# Generated by Django 3.1.1 on 2020-11-21 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mukesh', max_length=100)),
                ('address', models.CharField(default='Antilla, Mumbai', max_length=500)),
                ('contactNo', models.CharField(default='0000000000', max_length=15)),
                ('ventilators', models.CharField(default='000000', max_length=5)),
                ('beds', models.CharField(default='000000', max_length=6)),
                ('occupiedVentilators', models.CharField(default='000000', max_length=5)),
                ('occupiedBeds', models.CharField(default='000000', max_length=6)),
                ('avilableOxygenCylinders', models.CharField(default='000000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='Mukesh', max_length=30)),
                ('lName', models.CharField(default='Ambani', max_length=30)),
                ('fullName', models.CharField(default='Mukesh Ambani', max_length=60)),
                ('email', models.CharField(default='patient@patient.com', max_length=50)),
                ('age', models.CharField(default='000', max_length=3)),
                ('address', models.CharField(default='Antilla, Mumbai', max_length=500)),
                ('currentStatus', models.CharField(default='Active', max_length=10)),
                ('remarks', models.CharField(default='Recovering Steadily', max_length=1200)),
                ('medicalHistory', models.CharField(default='Diabetic', max_length=1200)),
                ('ventilator', models.BooleanField()),
                ('contactNo', models.CharField(default='0000000000', max_length=15)),
                ('patientID', models.CharField(default='A1A1A1', max_length=12)),
                ('isAlive', models.BooleanField()),
                ('operatedByDoctor', models.CharField(default='Vijay Raaz', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='StatusForChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('currentActive', models.CharField(default='000000', max_length=6)),
                ('currentDeceased', models.CharField(default='000000', max_length=6)),
                ('currentRecovered', models.CharField(default='000000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='Mukesh', max_length=30)),
                ('lName', models.CharField(default='Ambani', max_length=30)),
                ('fullName', models.CharField(default='Mukesh Ambani', max_length=60)),
                ('staffID', models.CharField(default='A1A1A1', max_length=12)),
                ('contactNo', models.CharField(default='0000000000', max_length=15)),
                ('email', models.CharField(default='patient@patient.com', max_length=50)),
                ('address', models.CharField(default='Antilla, Mumbai', max_length=500)),
                ('shift', models.CharField(default='Morning', max_length=10)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='Mukesh', max_length=30)),
                ('lName', models.CharField(default='Ambani', max_length=30)),
                ('fullName', models.CharField(default='Mukesh Ambani', max_length=60)),
                ('staffID', models.CharField(default='A1A1A1', max_length=12)),
                ('contactNo', models.CharField(default='0000000000', max_length=15)),
                ('email', models.CharField(default='patient@patient.com', max_length=50)),
                ('address', models.CharField(default='Antilla, Mumbai', max_length=500)),
                ('shift', models.CharField(default='Morning', max_length=10)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='Mukesh', max_length=30)),
                ('lName', models.CharField(default='Ambani', max_length=30)),
                ('fullName', models.CharField(default='Mukesh Ambani', max_length=60)),
                ('adminID', models.CharField(default='A1A1A1', max_length=12)),
                ('contactNo', models.CharField(default='0000000000', max_length=15)),
                ('email', models.CharField(default='patient@patient.com', max_length=50)),
                ('address', models.CharField(default='Antilla, Mumbai', max_length=500)),
                ('shift', models.CharField(default='Morning', max_length=10)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(default='Mukesh', max_length=30)),
                ('lName', models.CharField(default='Ambani', max_length=30)),
                ('fullName', models.CharField(default='Mukesh Ambani', max_length=60)),
                ('title', models.CharField(default='ENT Specialist', max_length=60)),
                ('contactNo', models.CharField(default='0000000000', max_length=15)),
                ('email', models.CharField(default='patient@patient.com', max_length=50)),
                ('address', models.CharField(default='Antilla, Mumbai', max_length=500)),
                ('doctorID', models.CharField(default='A1A1A1', max_length=12)),
                ('shift', models.CharField(default='Morning', max_length=10)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
