# Generated by Django 3.1.1 on 2020-11-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercuri', '0002_auto_20201121_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalAdmin',
        ),
    ]
