# Generated by Django 3.1.1 on 2020-11-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercuri', '0004_auto_20201121_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='hospitalstaff',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='photo',
        ),
    ]
