# Generated by Django 3.1.1 on 2020-11-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercuri', '0006_auto_20201121_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldata',
            name='occupiedBeds',
        ),
        migrations.RemoveField(
            model_name='hospitaldata',
            name='occupiedVentilators',
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(default='patient@patient.com', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(default='A1A1A1', max_length=12, unique=True),
        ),
    ]
