# Generated by Django 3.1.1 on 2020-11-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercuri', '0007_auto_20201121_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusforchart',
            name='currentTime',
        ),
    ]
